# Degişken Standardizasyonu(Veri Standardizasyonu)

In [3]:
#bilginin özünü bozmayız 

In [2]:
import numpy as np
import pandas as pd
V1=np.array([1,3,6,5,7])
V2=np.array([7,7,5,8,12])
V3=np.array([6,12,5,6,14])
df=pd.DataFrame(
{
    "V1":V1,
    "V2":V2,
    "V3":V3})
df=df.astype(float)
df

V1    V2    V3
0  1.0   7.0   6.0
1  3.0   7.0  12.0
2  6.0   5.0   5.0
3  5.0   8.0   6.0
4  7.0  12.0  14.0

## Standardizasyon

In [5]:
from sklearn import preprocessing

In [9]:
preprocessing.scale(df)#bu işlemi bütün degişkenlere uyguladı

array([[-1.57841037, -0.34554737, -0.70920814],
       [-0.64993368, -0.34554737,  0.92742603],
       [ 0.74278135, -1.2094158 , -0.98198051],
       [ 0.27854301,  0.08638684, -0.70920814],
       [ 1.2070197 ,  1.81412369,  1.47297076]])

In [13]:
df.mean()#dönüştürme yapılmamışların ortalaması 

V1    4.4
V2    7.8
V3    8.6
dtype: float64

## Normalizasyon

In [14]:
preprocessing.normalize(df)

array([[0.10783277, 0.75482941, 0.64699664],
       [0.21107926, 0.49251828, 0.84431705],
       [0.64699664, 0.53916387, 0.53916387],
       [0.4472136 , 0.71554175, 0.53665631],
       [0.35491409, 0.60842415, 0.70982818]])

## Min-Max Dönüşümü

In [17]:
scaler=preprocessing.MinMaxScaler(feature_range=(10,20))#nesne olarak oluşturdu

In [18]:
scaler.fit_transform(df)

array([[10.        , 12.85714286, 11.11111111],
       [13.33333333, 12.85714286, 17.77777778],
       [18.33333333, 10.        , 10.        ],
       [16.66666667, 14.28571429, 11.11111111],
       [20.        , 20.        , 20.        ]])

# **Degişken Dönüşümleri**

her bir standardizasyon bir degişken dönüşümüdür

In [20]:
import seaborn as sns
df=sns.load_dataset('tips')
df.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

## 0-1 Dönüşümü

female-male kısmını 1 ve 0 dönüştürme işlemi yapıyoruz 

In [23]:
from sklearn.preprocessing import LabelEncoder

lbe=LabelEncoder()

In [26]:
lbe.fit_transform(df["sex"])#veri setini dönüştürdü 

array([0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0,
       1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0,
       1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1,
       1, 0])

In [27]:
df["yeni_sex"]=lbe.fit_transform(df["sex"])

In [28]:
df#hangi kategorik degişkenin hangi degerine ne geldigini iyi anlamak gerekiyor 

total_bill   tip     sex smoker   day    time  size  yeni_sex
0         16.99  1.01  Female     No   Sun  Dinner     2         0
1         10.34  1.66    Male     No   Sun  Dinner     3         1
2         21.01  3.50    Male     No   Sun  Dinner     3         1
3         23.68  3.31    Male     No   Sun  Dinner     2         1
4         24.59  3.61  Female     No   Sun  Dinner     4         0
..          ...   ...     ...    ...   ...     ...   ...       ...
239       29.03  5.92    Male     No   Sat  Dinner     3         1
240       27.18  2.00  Female    Yes   Sat  Dinner     2         0
241       22.67  2.00    Male    Yes   Sat  Dinner     2         1
242       17.82  1.75    Male     No   Sat  Dinner     2         1
243       18.78  3.00  Female     No  Thur  Dinner     2         0

[244 rows x 8 columns]

## "1 ve Digerleri(0)"Dönüşümü

In [29]:
df.head()

total_bill   tip     sex smoker  day    time  size  yeni_sex
0       16.99  1.01  Female     No  Sun  Dinner     2         0
1       10.34  1.66    Male     No  Sun  Dinner     3         1
2       21.01  3.50    Male     No  Sun  Dinner     3         1
3       23.68  3.31    Male     No  Sun  Dinner     2         1
4       24.59  3.61  Female     No  Sun  Dinner     4         0

In [35]:
df["day"].str.contains("Sun")

0       True
1       True
2       True
3       True
4       True
       ...  
239    False
240    False
241    False
242    False
243    False
Name: day, Length: 244, dtype: bool

In [30]:
import numpy as np
df["yeni_day"]=np.where(df["day"].str.contains("Sun"),1,0)

In [31]:
df

total_bill   tip     sex smoker   day    time  size  yeni_sex  yeni_day
0         16.99  1.01  Female     No   Sun  Dinner     2         0         1
1         10.34  1.66    Male     No   Sun  Dinner     3         1         1
2         21.01  3.50    Male     No   Sun  Dinner     3         1         1
3         23.68  3.31    Male     No   Sun  Dinner     2         1         1
4         24.59  3.61  Female     No   Sun  Dinner     4         0         1
..          ...   ...     ...    ...   ...     ...   ...       ...       ...
239       29.03  5.92    Male     No   Sat  Dinner     3         1         0
240       27.18  2.00  Female    Yes   Sat  Dinner     2         0         0
241       22.67  2.00    Male    Yes   Sat  Dinner     2         1         0
242       17.82  1.75    Male     No   Sat  Dinner     2         1         0
243       18.78  3.00  Female     No  Thur  Dinner     2         0         0

[244 rows x 9 columns]

total_bill   tip     sex smoker   day    time  size  yeni_sex  yeni_day
0         16.99  1.01  Female     No   Sun  Dinner     2         0         1
1         10.34  1.66    Male     No   Sun  Dinner     3         1         1
2         21.01  3.50    Male     No   Sun  Dinner     3         1         1
3         23.68  3.31    Male     No   Sun  Dinner     2         1         1
4         24.59  3.61  Female     No   Sun  Dinner     4         0         1
..          ...   ...     ...    ...   ...     ...   ...       ...       ...
239       29.03  5.92    Male     No   Sat  Dinner     3         1         0
240       27.18  2.00  Female    Yes   Sat  Dinner     2         0         0
241       22.67  2.00    Male    Yes   Sat  Dinner     2         1         0
242       17.82  1.75    Male     No   Sat  Dinner     2         1         0
243       18.78  3.00  Female     No  Thur  Dinner     2         0         0

[244 rows x 9 columns]

## Çok sınıflı Dönüşüm

In [36]:
from sklearn.preprocessing import LabelEncoder
lbe=LabelEncoder()

In [37]:
lbe.fit_transform(df["day"])

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 3])

In [38]:
#cok dikkat

In [ ]:
#one-hot dönüşümü yapmamız lazım

# One-Hot Dönüşümü ve Dummy Değişken Tuzağı

In [5]:
import pandas as pd
import seaborn as sns
df=sns.load_dataset('tips')
df.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [8]:
df_one_hot=pd.get_dummies(df, columns=["sex"],prefix=["sex"])#prefix yapılacak olan degişimlerin ön isimlendirimesinin ne olacagını ifade etmektir

In [9]:
df_one_hot.head()

total_bill   tip smoker  day    time  size  sex_Male  sex_Female
0       16.99  1.01     No  Sun  Dinner     2         0           1
1       10.34  1.66     No  Sun  Dinner     3         1           0
2       21.01  3.50     No  Sun  Dinner     3         1           0
3       23.68  3.31     No  Sun  Dinner     2         1           0
4       24.59  3.61     No  Sun  Dinner     4         0           1

bir degişkeni ifade eden başka bir degişken varsa buna dummy degişken tuzagı denir

In [10]:
pd.get_dummies(df,columns=["day"],prefix=["day"]).head()

total_bill   tip     sex smoker    time  size  day_Thur  day_Fri  day_Sat  \
0       16.99  1.01  Female     No  Dinner     2         0        0        0   
1       10.34  1.66    Male     No  Dinner     3         0        0        0   
2       21.01  3.50    Male     No  Dinner     3         0        0        0   
3       23.68  3.31    Male     No  Dinner     2         0        0        0   
4       24.59  3.61  Female     No  Dinner     4         0        0        0   

   day_Sun  
0        1  
1        1  
2        1  
3        1  
4        1

one hot dönüşüm faydaları

1.genelde nümerik işlemler yaptıgımız için kullanırız 
2.kategorik degişkenler içindeki alt sınıfların etkilerini daha net hissederiz
3.birbirleri üzerinden oluşturulma durumunu ortadan kaldırır 
