In [1]:
import numpy as np
a=np.random.randint(10,size=(5,5,))
a

array([[7, 6, 5, 8, 6],
       [1, 2, 4, 9, 3],
       [1, 1, 4, 6, 1],
       [8, 5, 5, 0, 8],
       [6, 8, 0, 9, 2]])

In [ ]:
#alt kümede işlem yaparken ana parcası bozulmasın istiyorsak

In [2]:
alt_a=a[0:3,0:2]#ilk arrayin bir kısmını aldık
alt_a

array([[7, 6],
       [1, 2],
       [1, 1]])

In [3]:
alt_a[0,0]=9999
alt_a[1,1]=888

In [4]:
alt_a

array([[9999,    6],
       [   1,  888],
       [   1,    1]])

In [5]:
a#degişiklik ana arrayde de meydana geldi

array([[9999,    6,    5,    8,    6],
       [   1,  888,    4,    9,    3],
       [   1,    1,    4,    6,    1],
       [   8,    5,    5,    0,    8],
       [   6,    8,    0,    9,    2]])

In [ ]:
#yaptıgımız degişkliğin ana array üzerinde olmasını istemiyorsak

In [10]:
alt_b = a[0:3, 0:2].copy()#alt kümeyi ana arrayden bagımsızlaştırır ve yaptıgımız degişiklik ana arrayde oluşmadı.
alt_b

array([[9999,    6],
       [   1,  888],
       [   1,    1]])

In [11]:
alt_b[0,0]=3333

In [12]:
alt_b

array([[3333,    6],
       [   1,  888],
       [   1,    1]])

In [13]:
a

array([[9999,    6,    5,    8,    6],
       [   1,  888,    4,    9,    3],
       [   1,    1,    4,    6,    1],
       [   8,    5,    5,    0,    8],
       [   6,    8,    0,    9,    2]])