In [ ]:
#fancy =fantastik anlamına gelir
#ve daha ileri düzey eleman secme işine yarar
#çok önemli

In [2]:
import numpy as np
v= np.arange(0,30,3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [3]:
v[1]

3

In [4]:
v[3]

9

In [5]:
v[5]

15

In [6]:
[v[1],v[3],v[5]]# 3 tanesine aynı andd erişmek için liste yaparız

[3, 9, 15]

In [10]:
al_getir=[1,3,5]#1. 3. ve 5. indexteki elemanı getir

In [11]:
v[al_getir]# yukarıda seçtiklerimizi çagırma yaptık farklı bir şekilde,çok yüksek boyutlu araylerde işe yarar

array([ 3,  9, 15])

In [ ]:
#iki boyutta fancy index işlemi yapalım

In [14]:
m=np.arange(9).reshape((3,3))

In [15]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [16]:
satir=np.array([0,1])
sutun=np.array([1,2])

In [17]:
m[satir,sutun]

array([1, 5])

In [18]:
#basit index ile fancy index

In [19]:
m                

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [20]:
m[0,[1,2]]#fancy ile basit i kullandık

array([1, 2])

In [21]:
#slice ile fancy

In [22]:
m[0:,[1,2]]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [23]:
m[0,[1,2]]

array([1, 2])