In [2]:
import numpy as np

In [3]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [6]:
a=np.array([1,2,3,4,5])

In [7]:
type(a)

numpy.ndarray

In [8]:
np.array([3.14,4,2,13])#tek tip veri tutmadan dolayı bu şekile çevirir

array([ 3.14,  4.  ,  2.  , 13.  ])

In [12]:
np.array([3.14,4,2,13],dtype="int")

array([ 3,  4,  2, 13])

In [13]:
np.array([3.14,4,2,13],dtype="float")

array([ 3.14,  4.  ,  2.  , 13.  ])

In [ ]:
#sifirdan arrray oluşturma işlemi 

In [14]:
np.zeros(10)#parantez içine dtype=int yazarsak int veri yapısına dönüşür

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [16]:
np.ones((3,5))#parantez içine dtype=int yazarsak int yapısına dönüşür

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
#eğer sadece belirli bir sayıdan array oluşturmak istersek

In [17]:
np.full((3,5),3)#3'e 5'lik boyutunda 3 lerden oluşan bir array

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [ ]:
#dogrusal bir dizi oluşturmak için

In [18]:
np.arange(0,31, 3)#0 dan başlayıp 31'e kadar 3'er 3'er artan bir dizi oluşturmak için

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [ ]:
#iki deger arasında belirli sayıda deger oluşturmak için

In [19]:
np.linspace(0,1,10)#0 ila 1 arasında 10 tane sayı oluşturdu

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [ ]:
#iki boyutlu arrayin istedigimiz bir şeklilde dagılım özelligini taşıyacak şekilde yazmak istersek

In [24]:
np.random.normal(10, 4, (3,4))#ortalaması 10,standart sapmasının 4,(3,4)lük bir matris

array([[ 5.91385175, 11.95368991,  2.53742917, 11.3567782 ],
       [-0.75573469,  7.33844821,  2.33193574,  8.49789197],
       [ 4.78244348, 11.58821089, 19.98365375,  8.15127729]])

In [ ]:
#tek boyutlu arrayin karşılıgı vektordür
#iki boyutlu arrayin karşılıgı ise matristir

In [ ]:
#int degerlerden rastgele degerlerden oluşmuş bir array oluşturmak istersek

In [31]:
np.random.randint(0,10, (3,3))

array([[4, 6, 6],
       [4, 4, 1],
       [1, 1, 1]])