In [1]:
import numpy as np

In [2]:
x=np.array([1,2,3])
y=np.array([4,5,6])

In [3]:
np.concatenate([x,y])#iki array yan yana getirerek birleştirdi

array([1, 2, 3, 4, 5, 6])

In [4]:
z=np.array([7,8,9])

In [5]:
np.concatenate([x,y,z])#3 tane array i birleştirdik

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#İKİ boyutta birleştirme ise iki tane köşeli parantez ile yaparız

In [6]:
a=np.array([[1,2,3,],
            [4,5,6]])#okuması kolay olsun diye bir alt satıra in

In [7]:
np.concatenate([a,a])#satır bazında birleştirme bu şekilde

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [8]:
np.concatenate([a,a],axis=1)#axis eksen belirtmek için kullanılır

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])