In [1]:
import numpy as np

In [ ]:
#n index'e karşılık n+1 şeklinde index ayrılıyor

In [3]:
x=np.array([1,2,3,99,99,3,2,1])

In [4]:
np.split(x,[3,5])#x in 3. ve 5. indexinde ayır

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

In [5]:
a,b,c=np.split(x,[3,5])#a b c ye ayırdıgımız parçaların atamasını atama yaptık

In [6]:
a

array([1, 2, 3])

In [7]:
b

array([99, 99])

In [8]:
c

array([3, 2, 1])

In [ ]:
#iki boyutlu-daha karışık ayırma işlemi için

In [12]:
m=np.arange(16).reshape(4,4)


In [13]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [14]:
np.vsplit(m,[2])#2. indexe göre ayırma yaptık

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [15]:
ust,alt=np.vsplit(m,[2])#ust ve alt a ayrılmış olanların atamasını yaptık,dikey olarak yan yana kkoyma işlemi yaptı

In [16]:
ust

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [17]:
alt

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [18]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [19]:
np.hsplit(m,[2])#yatay olarak bölme işlmei yapmak için

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [20]:
sag,sol=np.hsplit(m,[2])

In [21]:
sag

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [22]:
sol

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])