In [1]:
import numpy as np

In [2]:
v=np.array([2,1,4,3,5])

In [3]:
v

array([2, 1, 4, 3, 5])

In [4]:
np.sort(v)#küçükten büyüge sıralama yaptı ama yapısını bozmadı

array([1, 2, 3, 4, 5])

In [5]:
v

array([2, 1, 4, 3, 5])

In [6]:
v.sort()#sort metodu arrayin yapısını degiştiriyor

In [7]:
v

array([1, 2, 3, 4, 5])

In [ ]:
#iki boyutlu

In [8]:
m=np.random.normal(20,5,(3,3))

In [9]:
m

array([[32.19165124, 24.98431093, 25.48563488],
       [29.99307501, 22.50653418, 21.4148772 ],
       [15.63103106, 21.76917198, 17.41975477]])

In [11]:
np.sort(m,axis=1)#satıra göre sıralama yaptık kendi içinde

array([[24.98431093, 25.48563488, 32.19165124],
       [21.4148772 , 22.50653418, 29.99307501],
       [15.63103106, 17.41975477, 21.76917198]])

In [12]:
np.sort(m,axis=0)#sutuna göre sıralama yapmak istersek 

array([[15.63103106, 21.76917198, 17.41975477],
       [29.99307501, 22.50653418, 21.4148772 ],
       [32.19165124, 24.98431093, 25.48563488]])