In [2]:
import numpy as np
a=np.random.randint(10, size=10)
a

array([9, 9, 3, 5, 4, 3, 3, 9, 8, 9])

In [3]:
a[0]#0. indexteki elemana eriştik

9

In [4]:
a[-2]#tersten elemana eriştik 

8

In [6]:
a[0]=100#0. indexteki elemanı degiştirdik

In [8]:
a

array([100,   9,   3,   5,   4,   3,   3,   9,   8,   9])

In [9]:
m=np.random.randint(10, size=(3,5))#3,5 kısmı ile array boyutunun belirttik,bunun yerine tek sayı girseydik tek boyutta array oluştururdu.
m

array([[4, 9, 2, 6, 0],
       [0, 7, 1, 5, 4],
       [1, 8, 7, 2, 8]])

In [10]:
m[0,0]

4

In [11]:
m[2,4]

8

In [12]:
m[1,4]=99#array deki sayıyı degiştirdik.

In [13]:
m

array([[ 4,  9,  2,  6,  0],
       [ 0,  7,  1,  5, 99],
       [ 1,  8,  7,  2,  8]])

In [ ]:
#tip degiştirme yaparken onu degiştirmek gerektigini unutma,degişim yapıp ekleyeceksende tip degişimi yapmayı unutma 