In [1]:
import numpy as np

In [3]:
a=np.arange(20,30)
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [4]:
a[0:3]#0. ile 3. arasında seç 

array([20, 21, 22])

In [5]:
a[:3]#baştan başla 3. ye kadar git

array([20, 21, 22])

In [6]:
a[3:]#3 ten başla sona kadar git

array([23, 24, 25, 26, 27, 28, 29])

In [7]:
a[1::2]#1. elemandan başla 2 şer 2şer atla git

array([21, 23, 25, 27, 29])

In [9]:
a[2::3]

array([22, 25, 28])

In [ ]:
#iki boyutta olanlarda slice işlemleri("," aracılıgı ile yaparız)

In [21]:
m=np.random.randint(10,size=(5,5))
m

array([[5, 9, 2, 8, 1],
       [7, 7, 2, 2, 6],
       [1, 8, 0, 5, 2],
       [5, 1, 7, 6, 2],
       [6, 8, 2, 1, 1]])

In [22]:
m[:,0] #0.sütünun tamanına erişti

array([5, 7, 1, 5, 6])

In [23]:
m[:,4]#4.sutun

array([1, 6, 2, 2, 1])

In [24]:
m[0,:]#0.satırın tamamına erişti

array([5, 9, 2, 8, 1])

In [25]:
m[2,:]

array([1, 8, 0, 5, 2])

In [26]:
m[0:2, 0:3]#0 dan 2 ye kadar satırları 0 dan 3e kadar sütünları

array([[5, 9, 2],
       [7, 7, 2]])

In [27]:
m[::,:2]#tüm satırları al ve ilk sütünu al

array([[5, 9],
       [7, 7],
       [1, 8],
       [5, 1],
       [6, 8]])

In [29]:
m[1:3,0:2]#0.satırı atla 1 den 3 e kadar olan satırı ve 0 dan 2 ye kadar olan sutünu al.

array([[7, 7],
       [1, 8]])